# generated by datamodel-codegen:
#   filename:  alldata.json
#   timestamp: 2026-03-18T13:35:29+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Element(BaseModel):
    id: int
    assists: int
    bonus: int
    bps: int
    clean_sheets: int
    creativity: str
    goals_conceded: int
    goals_scored: int
    ict_index: str
    influence: str
    minutes: int
    own_goals: int
    penalties_missed: int
    penalties_saved: int
    red_cards: int
    saves: int
    threat: str
    yellow_cards: int
    starts: int
    expected_goals: str
    expected_assists: str
    expected_goal_involvements: str
    expected_goals_conceded: str
    clearances_blocks_interceptions: int
    recoveries: int
    tackles: int
    defensive_contribution: int
    added: str
    chance_of_playing_next_round: int | None
    chance_of_playing_this_round: int | None
    code: int
    draft_rank: int
    dreamteam_count: int
    ep_next: str | None
    ep_this: None
    event_points: int
    first_name: str
    form: str
    in_dreamteam: bool
    news: str
    news_added: str | None
    news_return: None
    news_updated: None
    points_per_game: str
    second_name: str
    squad_number: None
    status: str
    total_points: int
    web_name: str
    influence_rank: int
    influence_rank_type: int
    creativity_rank: int
    creativity_rank_type: int
    threat_rank: int
    threat_rank_type: int
    ict_index_rank: int
    ict_index_rank_type: int
    form_rank: int | None
    form_rank_type: int | None
    points_per_game_rank: int | None
    points_per_game_rank_type: int | None
    corners_and_indirect_freekicks_order: None
    corners_and_indirect_freekicks_text: str
    direct_freekicks_order: None
    direct_freekicks_text: str
    penalties_order: None
    penalties_text: str
    element_type: int
    team: int


class ElementType(BaseModel):
    id: int
    element_count: int
    singular_name: str
    singular_name_short: str
    plural_name: str
    plural_name_short: str


class ElementStat(BaseModel):
    name: str
    label: str
    abbreviation: str
    is_match_stat: bool
    match_stat_order: int | None
    sort: str


class Datum(BaseModel):
    average_entry_score: None
    deadline_time: str
    id: int
    name: str
    finished: bool
    highest_scoring_entry: None
    trades_time: str
    waivers_time: str


class Events(BaseModel):
    current: int
    data: list[Datum]
    next: int


class Match(BaseModel):
    id: int
    started: bool
    code: int
    finished: bool
    finished_provisional: bool
    kickoff_time: str
    minutes: int
    provisional_start_time: bool
    team_a_score: None
    team_h_score: None
    pulse_id: int
    event: int
    team_a: int
    team_h: int



class Fixtures(BaseModel):
    dict[str, list[Match]]


class League(BaseModel):
    default_entries: int
    draft_reminder_hours: list[int]
    draft_postpone_hours: int
    draft_pushback_times: int
    draft_cutoff_hours: int
    max_drafts: int
    h2h_draw: int
    h2h_lose: int
    h2h_win: int
    max_entries: int
    min_entries: int
    private_max: int
    public_draft_delay_minutes: int
    public_draft_tz_default: str
    public_entry_sizes: list[int]
    public_max: int


class Scoring(BaseModel):
    long_play_limit: int
    short_play: int
    long_play: int
    concede_limit: int
    goals_conceded_GKP: int
    goals_conceded_DEF: int
    goals_conceded_MID: int
    goals_conceded_FWD: int
    saves_limit: int
    saves: int
    goals_scored_GKP: int
    goals_scored_DEF: int
    goals_scored_MID: int
    goals_scored_FWD: int
    assists: int
    clean_sheets_GKP: int
    clean_sheets_DEF: int
    clean_sheets_MID: int
    clean_sheets_FWD: int
    defensive_contribution_limit_GKP: int
    defensive_contribution_limit_DEF: int
    defensive_contribution_limit_MID: int
    defensive_contribution_limit_FWD: int
    defensive_contribution_GKP: int
    defensive_contribution_DEF: int
    defensive_contribution_MID: int
    defensive_contribution_FWD: int
    penalties_saved: int
    penalties_missed: int
    yellow_cards: int
    red_cards: int
    own_goals: int
    bonus: int


class PositionTypeLocks(BaseModel):
    field_12: str = Field(..., alias='12')


class Squad(BaseModel):
    size: int
    select_GKP: int
    select_DEF: int
    select_MID: int
    select_FWD: int
    play: int
    min_play_GKP: int
    max_play_GKP: int
    min_play_DEF: int
    max_play_DEF: int
    min_play_MID: int
    max_play_MID: int
    min_play_FWD: int
    max_play_FWD: int
    position_type_locks: PositionTypeLocks
    captains_disabled: bool


class Transactions(BaseModel):
    new_element_locked_hours: int
    trade_veto_minimum: int
    trade_veto_hours: int
    waivers_before_start_min_hours: int
    waivers_before_deadline_hours: int
    waivers_before_deadline_hours_event: dict[str, Any]


class Ui(BaseModel):
    special_shirt_exclusions: list[Any]
    use_special_shirts: bool


class Settings(BaseModel):
    league: League
    scoring: Scoring
    squad: Squad
    transactions: Transactions
    ui: Ui


class Team(BaseModel):
    code: int
    id: int
    name: str
    pulse_id: int
    short_name: str


class Model(BaseModel):
    elements: list[Element]
    element_types: list[ElementType]
    element_stats: list[ElementStat]
    events: Events
    fixtures: Fixtures
    settings: Settings
    teams: list[Team]
